[package]
name = "ecc"
version = "0.1.0"
edition = "2021"

[dependencies]
kangarootwelve_xkcp = "0.1.5"

[dependencies.gmp-mpfr-sys]
version = "1.6"
default-features = false
features = ["use-system-libs"]

[dependencies.rug]
version = "1.28"
default-features = false
features = ["integer", "std", "rand"]